### ISSUE TITLE
update account linking is not working

### ISSUE THREAD

**Issue by xavidop** [alexa/ask-cli#335]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

When Ia try to run the command:
ask smapi update-account-linking-info -s <skill-id> --account-linking-request file:skill-package/account-linking/account-linking-info.json --debug --full-response

It does not work.

The content of the file in skill-package/account-linking/account-linking-info.json is:
```json
{
      "accessTokenScheme": "HTTP_BASIC",
      "accessTokenUrl": "https://api.amazon.com/auth/o2/token",
      "authorizationUrl": "https://www.amazon.com/ap/oa",
      "clientId": "amzn1.application-oa2-client.45e3f8097e584335ae186a593195bef7",
      "domains": [],
      "scopes": [
        "profile"
      ],
      "skipOnEnablement": true,
      "type": "AUTH_CODE"
}
```
I've tried as well with this json and same result:
```json
{
  "accountLinkingRequest": {
    "accessTokenScheme": "HTTP_BASIC",
    "accessTokenUrl": "https://api.amazon.com/auth/o2/token",
    "authorizationUrl": "https://www.amazon.com/ap/oa",
    "clientId": "amzn1.application-oa2-client.45e3f8097e584335ae186a593195bef7",
    "domains": [],
    "scopes": [
      "profile"
    ],
    "skipOnEnablement": true,
    "type": "AUTH_CODE"
  }
}
```

## Expected Behavior
It should create/update the acount linking info

## Current Behavior
it is not working. I have always the same output. Server cannot process the request due to a client error e.g. Authorization Url is invalid.

**CLI Snapshot**
![image](https://user-images.githubusercontent.com/4416096/98719493-1d5f9c00-2390-11eb-9c96-0a5b75860abc.png)

## Steps to Reproduce (for bugs)
Try the command above with any skill. My skill is a self hosted one (AWS lambda created from the ASK CLI)

## Your Environment and Context

* ask-cli version: 2.19.3
* Operating System and version: Windows 10
* Node.js version used for development: Node.js v10.19.0
* NPM version used for development: 6.13.4

**Comment by kakhaUrigashvili** [comment]
@xavidop please use version 2.20.0 and above. It should show you a validation error, explaining why the server is not able to process the request.

**Comment by xavidop** [comment]
I have now this output:

  "detail": {
    "name": "ServiceError",
    "statusCode": 400,
    "headers": [
      {
        "key": "content-type",
        "value": "application/json"
      },
      {
        "key": "content-length",
        "value": "254"
      },
      {
        "key": "connection",
        "value": "close"
      },
      {
        "key": "server",
        "value": "Server"
      },
      {
        "key": "date",
        "value": "Tue, 10 Nov 2020 19:26:33 GMT"
      },
      {
        "key": "x-amz-rid",
        "value": "D1H5H9BF4VGN0EMG5S3Y"
      },
      {
        "key": "x-amzn-requestid",
        "value": "b6381025-bcd2-4751-9230-48339c585dd8"
      },
      {
        "key": "x-amz-date",
        "value": "Tue, 10 Nov 2020 19:26:33 GMT"
      },
      {
        "key": "vary",
        "value": "Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent"
      },
      {
        "key": "x-cache",
        "value": "Error from cloudfront"
      },
      {
        "key": "via",
        "value": "1.1 844de3d616579278fb702fc6b9b5c9a3.cloudfront.net (CloudFront)"
      },
      {
        "key": "x-amz-cf-pop",
        "value": "ARN1-C1"
      },
      {
        "key": "x-amz-cf-id",
        "value": "go-LOucyWpK0ylUUiFlDQIQBJwiZS8tcc8vYi4Bc1ba9GjlovZqMuw=="
      }
    ],
    "response": {
      "message": "Account linking information is not valid.",
      "violations": [
        {
          "code": "INVALID_REQUEST_PARAMETER",
          "message": "Parsing error due to empty body.",
          "validationDetails": {
            "originalInstance": {
              "type": "BODY"
            },
            "reason": {
              "type": "EXPECTED_NOT_EMPTY_VALUE"
            }
          }
        }
      ]
    }
  }
}

but I do not what is empty. can you help me with that? json seems ok

thank you!
Xavi

**Comment by xavidop** [comment]
I've try this json:

{
    "accountLinkingRequest": {

      "accessTokenScheme": "HTTP_BASIC",
      "accessTokenUrl": "https://api.amazon.com/auth/o2/token",
      "authorizationUrl": "https://www.amazon.com/ap/oa",
      "clientId": "amzn1.application-oa2-client.45e3f8097e584335ae186a593195bef7",
      "clientSecret": "MY-SECRET",
      "scopes": [
        "profile"
      ],
      "skipOnEnablement": true,
      "type": "AUTH_CODE"
    }
}

and it is solved!

**Comment by RonWang** [comment]
Haha yes, the top level key "accountLinkingRequest" is needed; and you missed the "clientSecret" in your first JSON

**Comment by xavidop** [comment]
hahah yeeah, now with a clear explanation of the error in 1 minute I fixed it!

Thank you anyway!
Xavi
